# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spider.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 800)
        Form.setMinimumSize(QtCore.QSize(800, 800))
        Form.setMaximumSize(QtCore.QSize(800, 800))
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 771, 771))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.qr_label = QtWidgets.QLabel(self.widget)
        self.qr_label.setGeometry(QtCore.QRect(20, 10, 300, 300))
        self.qr_label.setMinimumSize(QtCore.QSize(300, 300))
        self.qr_label.setMaximumSize(QtCore.QSize(300, 300))
        self.qr_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.qr_label.setText("")
        self.qr_label.setObjectName("qr_label")
        self.update_qr_btn = QtWidgets.QPushButton(self.widget)
        self.update_qr_btn.setGeometry(QtCore.QRect(60, 330, 75, 23))
        self.update_qr_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.update_qr_btn.setObjectName("update_qr_btn")
        self.update_qr_btn_2 = QtWidgets.QPushButton(self.widget)
        self.update_qr_btn_2.setGeometry(QtCore.QRect(190, 330, 75, 23))
        self.update_qr_btn_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.update_qr_btn_2.setObjectName("update_qr_btn_2")
        self.login_status_bro = QtWidgets.QTextBrowser(self.widget)
        self.login_status_bro.setGeometry(QtCore.QRect(20, 370, 301, 61))
        self.login_status_bro.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"宋体\";")
        self.login_status_bro.setObjectName("login_status_bro")
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(332, 0, 31, 771))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setGeometry(QtCore.QRect(10, 450, 331, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.career_edit = QtWidgets.QLineEdit(self.widget)
        self.career_edit.setGeometry(QtCore.QRect(110, 480, 191, 20))
        self.career_edit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.career_edit.setObjectName("career_edit")
        self.comp_edit = QtWidgets.QLineEdit(self.widget)
        self.comp_edit.setGeometry(QtCore.QRect(110, 540, 191, 20))
        self.comp_edit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comp_edit.setObjectName("comp_edit")
        self.provice_comb = QtWidgets.QComboBox(self.widget)
        self.provice_comb.setGeometry(QtCore.QRect(20, 630, 101, 22))
        self.provice_comb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.provice_comb.setObjectName("provice_comb")
        self.major_edit = QtWidgets.QLineEdit(self.widget)
        self.major_edit.setGeometry(QtCore.QRect(110, 570, 191, 20))
        self.major_edit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.major_edit.setObjectName("major_edit")
        self.city_comb = QtWidgets.QComboBox(self.widget)
        self.city_comb.setGeometry(QtCore.QRect(120, 630, 101, 22))
        self.city_comb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.city_comb.setObjectName("city_comb")
        self.area_comb = QtWidgets.QComboBox(self.widget)
        self.area_comb.setGeometry(QtCore.QRect(220, 630, 101, 22))
        self.area_comb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.area_comb.setObjectName("area_comb")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(50, 610, 54, 12))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(140, 610, 54, 12))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(240, 610, 54, 12))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QtCore.QRect(120, 690, 75, 23))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.exmple_display_bro = QtWidgets.QTextBrowser(self.widget)
        self.exmple_display_bro.setGeometry(QtCore.QRect(360, 10, 401, 301))
        self.exmple_display_bro.setStyleSheet("font: 14pt \"宋体\";\n"
"background-color: rgb(255, 255, 255);")
        self.exmple_display_bro.setObjectName("exmple_display_bro")
        self.line_3 = QtWidgets.QFrame(self.widget)
        self.line_3.setGeometry(QtCore.QRect(350, 370, 411, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 330, 75, 23))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.result_bro = QtWidgets.QTextBrowser(self.widget)
        self.result_bro.setGeometry(QtCore.QRect(360, 390, 401, 371))
        self.result_bro.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"宋体\";")
        self.result_bro.setObjectName("result_bro")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(620, 330, 75, 23))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.work_type_edit = QtWidgets.QLineEdit(self.widget)
        self.work_type_edit.setGeometry(QtCore.QRect(110, 510, 191, 20))
        self.work_type_edit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.work_type_edit.setObjectName("work_type_edit")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(40, 480, 61, 21))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"宋体\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(40, 510, 61, 21))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"宋体\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(40, 540, 61, 21))
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"宋体\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(40, 570, 61, 21))
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"宋体\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(360, 330, 121, 21))
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"宋体\";")
        self.label_8.setObjectName("label_8")
        self.delay_comb = QtWidgets.QComboBox(self.widget)
        self.delay_comb.setGeometry(QtCore.QRect(480, 330, 51, 22))
        self.delay_comb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.delay_comb.setObjectName("delay_comb")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(220, 750, 121, 21))
        self.label_9.setObjectName("label_9")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(710, 330, 41, 23))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Form)
        self.update_qr_btn.clicked.connect(Form.update_qr)
        self.update_qr_btn_2.clicked.connect(Form.get_cookie)
        self.provice_comb.currentIndexChanged['QString'].connect(Form.set_city_items)
        self.city_comb.currentIndexChanged['QString'].connect(Form.set_area_items)
        self.pushButton.clicked.connect(Form.talents_search)
        self.pushButton_2.clicked.connect(Form.resume_spider)
        self.pushButton_3.clicked.connect(Form.stop_spider)
        self.pushButton_4.clicked.connect(Form.clear_result_browser)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "智联简历自动化系统"))
        self.update_qr_btn.setText(_translate("Form", "刷新二维码"))
        self.update_qr_btn_2.setText(_translate("Form", "扫码成功"))
        self.login_status_bro.setPlaceholderText(_translate("Form", "登录状态展示面板 \n尚未登录，请扫码登录。"))
        self.career_edit.setPlaceholderText(_translate("Form", "请输入候选人职位名称关键词"))
        self.comp_edit.setPlaceholderText(_translate("Form", "请输入公司名称关键词"))
        self.major_edit.setPlaceholderText(_translate("Form", "多个专业可用空格分隔"))
        self.label.setText(_translate("Form", "期望省市"))
        self.label_2.setText(_translate("Form", "期望城市"))
        self.label_3.setText(_translate("Form", "期望区镇"))
        self.pushButton.setText(_translate("Form", "人才搜索"))
        self.exmple_display_bro.setPlaceholderText(_translate("Form", "搜索结果展示面板"))
        self.pushButton_2.setText(_translate("Form", "简历爬取"))
        self.result_bro.setPlaceholderText(_translate("Form", "爬取结果展示面板"))
        self.pushButton_3.setText(_translate("Form", "停止爬取"))
        self.work_type_edit.setPlaceholderText(_translate("Form", "请输入工作及项目经验关键词"))
        self.label_4.setText(_translate("Form", "职位名称："))
        self.label_5.setText(_translate("Form", "工作内容："))
        self.label_6.setText(_translate("Form", "公司名称："))
        self.label_7.setText(_translate("Form", "专业名称："))
        self.label_8.setText(_translate("Form", "延时设置(默认2s)："))
        self.label_9.setText(_translate("Form", "whitespace：白色空间"))
        self.pushButton_4.setText(_translate("Form", "清屏"))

